class SubCategoryData {
  final String image,
      price,
      weight,
      name,
      category,
      image1,
      image2,
      image3,
      image4;
  int quantity;

  SubCategoryData(this.image, this.price, this.weight, this.name, this.category,
      this.image1, this.image2, this.image3, this.image4, this.quantity);
}

List<SubCategoryData> milkList = [
  SubCategoryData(
      "assets/images/milk.png",
      "1",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Milk",
      "assets/images/milk_1_1.png",
      "assets/images/milk_1_2.png",
      "assets/images/milk_1_3.png",
      "assets/images/milk_1_4.png",
      0), //call the constructor of SubCategoryData
  SubCategoryData(
      "assets/images/milk1.png",
      "5",
      "22 mg",
      "Lactaid Whole Pure Milk",
      "Milk",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      0),
  SubCategoryData(
      "assets/images/milk2.png",
      "25",
      "20 mg",
      "Lactaid Fat Free Milk",
      "Milk",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      0),
  SubCategoryData(
      "assets/images/milk3.png",
      "45",
      "22 mg",
      "Lactaid Whole Milk",
      "Milk",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      0),
  SubCategoryData(
      "assets/images/milk.png",
      "15",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Milk",
      "assets/images/milk_1_1.png",
      "assets/images/milk_1_2.png",
      "assets/images/milk_1_3.png",
      "assets/images/milk_1_4.png",
      0), //call the constructor of SubCategoryData
  SubCategoryData(
      "assets/images/milk1.png",
      "35",
      "22 mg",
      "Lactaid Whole Pure Milk",
      "Milk",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      0),
  SubCategoryData(
      "assets/images/milk2.png",
      "25",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Milk",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      0),
  SubCategoryData(
      "assets/images/milk3.png",
      "45",
      "22 mg",
      "Lactaid Whole Pure Milk",
      "Milk",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      0),
  SubCategoryData(
      "assets/images/milk.png",
      "15",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Milk",
      "assets/images/milk_1_1.png",
      "assets/images/milk_1_2.png",
      "assets/images/milk_1_3.png",
      "assets/images/milk_1_4.png",
      0), //call the constructor of SubCategoryData
  SubCategoryData(
      "assets/images/milk1.png",
      "35",
      "22 mg",
      "Lactaid Whole Pure Milk",
      "Milk",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      "assets/images/milk1.png",
      0),
  SubCategoryData(
      "assets/images/milk2.png",
      "25",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Milk",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      "assets/images/milk2.png",
      0),
  SubCategoryData(
      "assets/images/milk3.png",
      "45",
      "22 mg",
      "Lactaid Whole Pure Milk",
      "Milk",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      "assets/images/milk3.png",
      0),
];

List<SubCategoryData> iceCreamList = [
  SubCategoryData(
      "assets/images/ice_cream.png",
      "15",
      "20 mg",
      "Birthday Special Ice -cream",
      "Ice Cream",
      "assets/images/ice_cream.png",
      "assets/images/ice_cream.png",
      "assets/images/ice_cream.png",
      "assets/images/ice_cream.png",
      0),
  SubCategoryData(
      "assets/images/ice_cream1.png",
      "35",
      "20 mg",
      "Purpule Yam Ice Cream",
      "Ice Cream",
      "assets/images/ice_cream1.png",
      "assets/images/ice_cream1.png",
      "assets/images/ice_cream1.png",
      "assets/images/ice_cream1.png",
      0),
  SubCategoryData(
      "assets/images/ice_cream2.png",
      "15",
      "20 mg",
      "Birthday Special Ice -cream",
      "Ice Cream",
      "assets/images/ice_cream2.png",
      "assets/images/ice_cream2.png",
      "assets/images/ice_cream2.png",
      "assets/images/ice_cream2.png",
      0),
  SubCategoryData(
      "assets/images/ice_cream3.png",
      "35",
      "20 mg",
      "Purpule Yam Ice Cream",
      "Ice Cream",
      "assets/images/ice_cream3.png",
      "assets/images/ice_cream3.png",
      "assets/images/ice_cream3.png",
      "assets/images/ice_cream3.png",
      0),
];

List<SubCategoryData> chipsList = [
  SubCategoryData(
      "assets/images/snacks_1.png",
      "15",
      "20 mg",
      "Lactaid Fat Free Pure Milk",
      "Chips",
      "assets/images/snacks_1.png",
      "assets/images/snacks_1.png",
      "assets/images/snacks_1.png",
      "assets/images/snacks_1.png",
      0),
  SubCategoryData(
      "assets/images/snacks_2.png",
      "35",
      "22 mg",
      "Lactaid Whole Pure Chips",
      "Chips",
      "assets/images/snacks_2.png",
      "assets/images/snacks_2.png",
      "assets/images/snacks_2.png",
      "assets/images/snacks_2.png",
      0),
];
List<SubCategoryData> fishList = [
  SubCategoryData(
      "assets/images/fish.png",
      "15",
      "20 mg",
      "Your Special Fish",
      "Fish",
      "assets/images/fish.png",
      "assets/images/fish.png",
      "assets/images/fish.png",
      "assets/images/fish.png",
      0),
];
